<?php

if(function_exists("register_field_group"))
{
  register_field_group(array (
    'id' => 'acf_emails',
    'title' => 'Emails',
    'fields' => array (
      array (
        'key' => 'field_5380b6a446f29',
        'label' => 'Email newsletter subscriptions to',
        'name' => 'subscription_email',
        'type' => 'text',
        'instructions' => 'Enter a comma separated list of email addresses',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_5380c3f59400e',
        'label' => 'Subject for newsletter subscription confirmation email',
        'name' => 'subscription_email_subject',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_5380c4159400f',
        'label' => 'Message for newsletter subscription confirmation email',
        'name' => 'subscription_email_message',
        'type' => 'textarea',
        'instructions' => ':name and :email will be replaced with the actual values from the subscription',
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'formatting' => 'none',
      ),
      array (
        'key' => 'field_5380b6c746f2a',
        'label' => 'Email event registrations to',
        'name' => 'event_registration_email',
        'type' => 'text',
        'instructions' => 'Enter a comma separated list of email addresses',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_5383590e8152d',
        'label' => 'Subject for event registration confirmation email',
        'name' => 'event_registration_email_subject',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_538359128152e',
        'label' => 'Message for event registration confirmation email',
        'name' => 'event_registration_email_message',
        'type' => 'textarea',
        'instructions' => ':name, :event_name, :event_link, :price_option_name and :amount will be replaced with the actual values from the registration. (Note that amount will have to be prefixed with the currency)',
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'formatting' => 'none',
      ),
      array (
        'key' => 'field_5380b6fb46f2b',
        'label' => 'Email consultation registrations to',
        'name' => 'consultation_registration_email',
        'type' => 'text',
        'instructions' => 'Enter a comma separated list of email addresses',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_5384230e9e58d',
        'label' => 'Subject for consultation registration confirmation email',
        'name' => 'consultation_registration_email_subject',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_538423119e58e',
        'label' => 'Message for consultation registration confirmation email',
        'name' => 'consultation_registration_email_message',
        'type' => 'textarea',
        'instructions' => ':name, :price_option_name and :amount will be replaced with the actual values from the registration. (Note that amount will have to be prefixed with the currency)',
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'formatting' => 'none',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-email',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'no_box',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
}
