<?php

// Field groups for navigation

if(function_exists("register_field_group"))
{
  register_field_group(array (
    'id' => 'acf_navigation-2',
    'title' => 'Navigation',
    'fields' => array (
      array (
        'key' => 'field_531869b392ddd',
        'label' => 'Main Navigation',
        'name' => 'main_nav',
        'type' => 'repeater',
        'sub_fields' => array (
          array (
            'key' => 'field_531869c592dde',
            'label' => 'Name',
            'name' => 'name',
            'type' => 'text',
            'column_width' => '',
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'formatting' => 'html',
            'maxlength' => '',
          ),
          array (
            'key' => 'field_53186abcd2856',
            'label' => 'Default Sidebar Image',
            'name' => 'default_sidebar_image',
            'type' => 'image',
            'column_width' => '',
            'save_format' => 'object',
            'preview_size' => 'post-thumbnail',
            'library' => 'all',
          ),
          array (
            'key' => 'field_531869ea92ddf',
            'label' => 'Sections',
            'name' => 'sections',
            'type' => 'repeater',
            'column_width' => '',
            'sub_fields' => array (
              array (
                'key' => 'field_53186a0992de0',
                'label' => 'Name',
                'name' => 'name',
                'type' => 'text',
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
              ),
              array (
                'key' => 'field_53186a1792de1',
                'label' => 'Links',
                'name' => 'links',
                'type' => 'flexible_content',
                'column_width' => '',
                'layouts' => array (
                  array (
                    'label' => 'Page Link',
                    'name' => 'page_link',
                    'display' => 'row',
                    'min' => '',
                    'max' => '',
                    'sub_fields' => array (
                      array (
                        'key' => 'field_53186a3d92de2',
                        'label' => 'Name',
                        'name' => 'name',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                      ),
                      array (
                        'key' => 'field_53186a5292de3',
                        'label' => 'Page',
                        'name' => 'url',
                        'type' => 'page_link',
                        'column_width' => '',
                        'post_type' => array (
                          0 => 'page',
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                      ),
                    ),
                  ),
                  array (
                    'label' => 'External Link',
                    'name' => 'external_link',
                    'display' => 'row',
                    'min' => '',
                    'max' => '',
                    'sub_fields' => array (
                      array (
                        'key' => 'field_53186a8392de5',
                        'label' => 'Name',
                        'name' => 'name',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                      ),
                      array (
                        'key' => 'field_53186a9592de6',
                        'label' => 'URL',
                        'name' => 'url',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => 'http://',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                      ),
                    ),
                  ),
                ),
                'button_label' => 'Add Link',
                'min' => '',
                'max' => '',
              ),
            ),
            'row_min' => '',
            'row_limit' => '',
            'layout' => 'row',
            'button_label' => 'Add Section',
          ),
        ),
        'row_min' => 1,
        'row_limit' => '',
        'layout' => 'row',
        'button_label' => 'Add Menu Item',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-navigation',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'no_box',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
}
