<?php

if(function_exists("register_field_group"))
{
  register_field_group(array (
    'id' => 'acf_registrations',
    'title' => 'Registrations',
    'fields' => array (
      array (
        'key' => 'field_53835a4938d7d',
        'label' => 'Name',
        'name' => 'name',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_53835a5b38d7e',
        'label' => 'Email',
        'name' => 'email',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_53835a6338d7f',
        'label' => 'Phone',
        'name' => 'phone',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_53835a6a38d80',
        'label' => 'Address',
        'name' => 'address',
        'type' => 'textarea',
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'formatting' => 'none',
      ),
      array (
        'key' => 'field_53835a7238d81',
        'label' => 'Comments',
        'name' => 'comments',
        'type' => 'textarea',
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'formatting' => 'none',
      ),
      array (
        'key' => 'field_53835a8c38d82',
        'label' => 'Consultation',
        'name' => 'consultation',
        'type' => 'true_false',
        'message' => '',
        'default_value' => 0,
      ),
      array (
        'key' => 'field_53835a9c38d83',
        'label' => 'Event',
        'name' => 'event',
        'type' => 'post_object',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_53835a8c38d82',
              'operator' => '!=',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'post_type' => array (
          0 => 'events',
        ),
        'taxonomy' => array (
          0 => 'all',
        ),
        'allow_null' => 0,
        'multiple' => 0,
      ),
      array (
        'key' => 'field_5383609e116b2',
        'label' => 'Price Option',
        'name' => 'price_option',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_538360ef116b3',
        'label' => 'Amount',
        'name' => 'amount',
        'type' => 'number',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'min' => '',
        'max' => '',
        'step' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'registration',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'no_box',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
}
