<?php

if(function_exists("register_field_group"))
{
  register_field_group(array (
    'id' => 'acf_resources',
    'title' => 'Resources',
    'fields' => array (
      array (
        'key' => 'field_537b29a3f2d20',
        'label' => 'Categories',
        'name' => 'categories',
        'type' => 'repeater',
        'sub_fields' => array (
          array (
            'key' => 'field_537b29baf2d21',
            'label' => 'Category Name',
            'name' => 'name',
            'type' => 'text',
            'required' => 1,
            'column_width' => '',
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'formatting' => 'none',
            'maxlength' => '',
          ),
          array (
            'key' => 'field_537b29c6f2d22',
            'label' => 'Books',
            'name' => 'books',
            'type' => 'repeater',
            'column_width' => '',
            'sub_fields' => array (
              array (
                'key' => 'field_537b29d9f2d23',
                'label' => 'Name',
                'name' => 'name',
                'type' => 'text',
                'required' => 1,
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
              ),
              array (
                'key' => 'field_537b29e8f2d24',
                'label' => 'Author',
                'name' => 'author',
                'type' => 'text',
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
              ),
              array (
                'key' => 'field_537b29f1f2d25',
                'label' => 'Image',
                'name' => 'image',
                'type' => 'image',
                'column_width' => '',
                'save_format' => 'object',
                'preview_size' => 'thumbnail',
                'library' => 'all',
              ),
              array (
                'key' => 'field_537b2a04f2d26',
                'label' => 'Description',
                'name' => 'description',
                'type' => 'wysiwyg',
                'column_width' => '',
                'default_value' => '',
                'toolbar' => 'basic',
                'media_upload' => 'no',
              ),
              array (
                'key' => 'field_537b2a33f2d27',
                'label' => 'Buy Link',
                'name' => 'buy_link',
                'type' => 'text',
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
              ),
            ),
            'row_min' => '',
            'row_limit' => '',
            'layout' => 'row',
            'button_label' => 'Add Book',
          ),
          array (
            'key' => 'field_537b2a4df2d28',
            'label' => 'Links',
            'name' => 'links',
            'type' => 'repeater',
            'column_width' => '',
            'sub_fields' => array (
              array (
                'key' => 'field_537b2c02f2d29',
                'label' => 'Name',
                'name' => 'name',
                'type' => 'text',
                'required' => 1,
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
              ),
              array (
                'key' => 'field_537b2c16f2d2a',
                'label' => 'Link',
                'name' => 'link',
                'type' => 'text',
                'required' => 1,
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
              ),
              array (
                'key' => 'field_537b2c73f2d2b',
                'label' => 'Description',
                'name' => 'description',
                'type' => 'wysiwyg',
                'column_width' => '',
                'default_value' => '',
                'toolbar' => 'basic',
                'media_upload' => 'no',
              ),
            ),
            'row_min' => '',
            'row_limit' => '',
            'layout' => 'row',
            'button_label' => 'Add Link',
          ),
        ),
        'row_min' => 1,
        'row_limit' => '',
        'layout' => 'row',
        'button_label' => 'Add Category',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'resources-page-template.php',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'no_box',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
}
